// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKERL0nF1alcTl3wz78_29p5IvGOZTeCc',
    appId: '1:145607831260:web:6fec71a511690c5126ce19',
    messagingSenderId: '145607831260',
    projectId: 'flutterfire-ui-codelab-66038',
    authDomain: 'flutterfire-ui-codelab-66038.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-66038.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARMrupXehoCkum2RBWHJG8hUANwcrFUL0',
    appId: '1:145607831260:android:89d1488434f8fafe26ce19',
    messagingSenderId: '145607831260',
    projectId: 'flutterfire-ui-codelab-66038',
    storageBucket: 'flutterfire-ui-codelab-66038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgDNBLRWEHN6qfiexfo20HzueBfzQj7Bc',
    appId: '1:145607831260:ios:7bc4d527cdee167426ce19',
    messagingSenderId: '145607831260',
    projectId: 'flutterfire-ui-codelab-66038',
    storageBucket: 'flutterfire-ui-codelab-66038.appspot.com',
    iosBundleId: 'com.example.lottery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgDNBLRWEHN6qfiexfo20HzueBfzQj7Bc',
    appId: '1:145607831260:ios:7bc4d527cdee167426ce19',
    messagingSenderId: '145607831260',
    projectId: 'flutterfire-ui-codelab-66038',
    storageBucket: 'flutterfire-ui-codelab-66038.appspot.com',
    iosBundleId: 'com.example.lottery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKERL0nF1alcTl3wz78_29p5IvGOZTeCc',
    appId: '1:145607831260:web:255783aa96835a1626ce19',
    messagingSenderId: '145607831260',
    projectId: 'flutterfire-ui-codelab-66038',
    authDomain: 'flutterfire-ui-codelab-66038.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-66038.appspot.com',
  );
}
